name: Sepd_Rekit
version: 1.0.0
description: A plugin that provides region-based kits in Minecraft.
author: Sepd
main: dev.sepd.sepd_rekit.Sepd_Rekit

commands:
  createkit:
    description: Create a new kit.
    usage: /createkit <kitName>3
    permission: rekit.createkit

  selectregion:
    description: Start selecting points for a region.
    usage: /selectregion
    permission: rekit.selectregion

  createregion:
    description: Create a new region based on selected points.
    usage: /createregion <regionName>
    permission: rekit.createregion

  setregionkit:
    description: Set a kit for a specific region.
    usage: /setregionkit <regionName> <kitName>
    permission: rekit.setregionkit

  rekitreload:
    description: Reload the RekitPlugin configuration.
    usage: /rekitreload
    permission: rekit.reload

  getwand:
    description: Get the region selection wand.
    usage: /getwand
    permission: rekit.getwand
