# config.yml

messages:
  wand-selection-first: "&aWand selection started. Selected location: %location%"
  wand-selection-second: "&aWand selection completed. Region created. Selected location: %location%"
  kit-received: "&aReceived kit '%kit%' for region: %region%"
  no-kit-defined: "&cNo kit defined for region: %region%"
  inventory-cleared: "&aInventory cleared."
  wand-received: "&aWand received."
  region-created: "&aRegion '%region%' created."
  kit-saved: "&aKit '%kit%' saved for region: %region%"
  kit-deleted: "&aKit '%kit%' deleted for region: %region%"
  region-deleted: "&aRegion '%region%' deleted."
  offhand-set: "&aOffhand item set for kit '%kit%' in region: %region%"
  armor-set: "&aArmor set for kit '%kit%' in region: %region%"
  offhand-restored: "&aRestored offhand item for kit '%kit%' in region: %region%"
  armor-restored: "&aRestored armor for kit '%kit%' in region: %region%"
  offhand-not-found: "&cOffhand item not found for kit '%kit%' in region: %region%"
  armor-not-found: "&cArmor not found for kit '%kit%' in region: %region%"
  region-not-found: "&cRegion not found."

# Add any additional configuration options as needed
